### PR TITLE
2nd order kinematics added <3 Jimmy 

### PR DESCRIPTION
**Pull request by witherslayer67**
Hello, I have been on a quest to add 2nd order swerve kinematics to every single swerve bot in FNC for the past offseason, I have implemented it on bots such as 4290, 3506, 7763, all with amazing feedback. 

now what is 2nd order swerve kinematics? 

in short the idea is
- reduces "skew" so when you move x or y and rotate at the same time that x or y movement gets skewed in the direction of the rotation.

- 2nd order kinematics steps in and reduces that skew (and almost removes it), making your movements and odometry (telemetry) more accurate

now this is the more simpler way to do it, if you want a better version (i will be working on in the future) look at this whitepaper: 
[https://www.chiefdelphi.com/t/whitepaper-swerve-drive-skew-and-second-order-kinematics/416964](https://www.chiefdelphi.com/t/whitepaper-swerve-drive-skew-and-second-order-kinematics/416964)

and also Rembrandts has an interesting version of it: [https://github.com/FRC-4481-Team-Rembrandts/4481-robot-2023-public/blob/master/src/main/java/frc/team4481/lib/swerve/SecondOrderSwerveKinematics.java](https://github.com/FRC-4481-Team-Rembrandts/4481-robot-2023-public/blob/master/src/main/java/frc/team4481/lib/swerve/SecondOrderSwerveKinematics.java)

2910 themselves told me that they use rembrants 2nd order version, and 2910 owns SDS, so keep that in mind

so just test this out, let me know how it goes, enjoy <3

--
Stay Cool,
Jimmy McCosker
Past Omegabytes Lead Programmer / Member
[jimmy.mccosker@gmail.com](mailto:jimmy.mccosker@gmail.com)

"Words have power, but only when people will listen. When they won't, actions speak loud enough for anyone." -Ryosuke Takahashi

### CODE REVIEW

**Comment by MGuron** [comment]
We just tested this and our path planner autos already look a little better, thanks for the help

**Comment by witherslayer67** [comment]
Thanks for the consideration into your Swerve Base! I am working on an even better version, but it won't be ready to go for a while. What I gave you helps not completely eliminate skew, the next version will be pinpoint accurate. :] 
If yall have any questions feel free to reach out! 
--
Stay Cool,
Jimmy McCosker
Past Omegabytes Lead Programmer / Member
jimmy.mccosker@gmail.com

"Words have power, but only when people will listen. When they won't, actions speak loud enough for anyone." -Ryosuke Takahashi

**Comment by witherslayer67** [comment]
I added the sequel, little more advanced, based off the research paper :)

**Comment by witherslayer67** [comment]
added more crucial math

**Comment by viggy96** [comment]
Some of this functionality will be available in WPILib 2024. So this may not be necessary.

Or at least should be changed to take advantage of the methods in WPILib.

https://www.chiefdelphi.com/t/whitepaper-swerve-drive-skew-and-second-order-kinematics/416964/28?u=viggy96

**Comment by witherslayer67** [comment]
Yes, but the actual 2nd Order stuff will be good to use

**Review by MGuron — APPROVED** [review]

**Pull request merged**
